version: '2'

volumes:
  build:
    driver: local
  cache:
    external: true

services:
  test:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile  
    volumes:
      - cache:/cache
      - build:/build
    links:
      - db
    environment:
      PIP_NO_INPUT: 0
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  db: 
    image: postgres

  agent:
    image: johnhamer1/ansible
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "5432"
    command: ["probe.yml"]

  builder:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - build:/build
    entrypoint: "entrypoint.sh"
    command: ["pip", "wheel", "--no-index", "-f /build", "."]
